#set page(
  paper: "a4",
  flipped: true,
  margin: 1.5cm,
)
#set text(font: "GFS Neohellenic", size: 14pt)

#place(
  top + center,
  scope: "parent",
  float: true,
  text(1.4em, weight: "bold")[
    #h(1fr) {{tournament}} #h(2fr) {{discipline}} -- elimination #h(1fr)
  ],
)

// ----- Fencers (seed order: index 0 = seed 1) ----------------
// Generated by render_elim.py: #let fencers and #let is_bye arrays.
// Slots beyond the actual entry count are filled with [ #h(1em) ---] (bye).
{{fencers}}

// Standard 8-bracket seeding (1v8, 4v5, 2v7, 3v6)
#let seed_order = (
  1, 8,
  4, 5,
  2, 7,
  3, 6,
)

#v(1cm)

#grid(
  columns: (1fr,) * 4,
  align: center,
  text(weight: "bold")[Quarterfinals],
  text(weight: "bold")[Semifinals],
  text(weight: "bold")[Final],
  text(weight: "bold")[Winner],
)

#v(0.1cm)

// ----- The bracket ------------------------------------------
#let draw_w = 26.5cm
#let draw_h = 14.8cm

#let n = 8
#let col_count = 4
#let col_w = draw_w / col_count
#let row_h = draw_h / n

#let line_y(r, i) = {
  let step = calc.pow(2, r)
  (i * step + (step - 1) / 2 + 0.5) * row_h
}
#let entries(r) = calc.div-euclid(n, calc.pow(2, r))
#let x_start(r) = r * col_w + 0.15cm
#let x_end(r) = (r + 1) * col_w - 0.15cm

#let stroke_style = 0.5pt + black

#block(width: draw_w, height: draw_h, {
  // Rounds 0..2 (QF, SF, F)
  for r in range(0, 3) {
    let count = entries(r)
    let i = 0
    while i < count {
      let y = line_y(r, i)
      let xs = x_start(r)
      let xe = x_end(r)

      place(
        top + left,
        dx: xs,
        dy: y,
        line(length: xe - xs, stroke: stroke_style),
      )

      if calc.rem(i, 2) == 0 {
        let y2 = line_y(r, i + 1)
        let mid = (y + y2) / 2

        place(
          top + left,
          dx: xe,
          dy: y,
          line(angle: 90deg, length: y2 - y, stroke: stroke_style),
        )
        place(
          top + left,
          dx: xe,
          dy: mid,
          line(length: x_start(r + 1) - xe, stroke: stroke_style),
        )
      }
      i = i + 1
    }
  }

  // Winner line in column 4
  let winner_y = (line_y(2, 0) + line_y(2, 1)) / 2
  place(
    top + left,
    dx: x_end(2),
    dy: winner_y,
    line(length: x_end(3) - x_end(2), stroke: stroke_style),
  )

  // Fencer names above their quarterfinal lines, with right-aligned seed.
  // Byes are shown in grey without changing the seed number.
  for i in range(0, 8) {
    let seed = seed_order.at(i)
    let name = fencers.at(seed - 1)
    let bye = is_bye.at(seed - 1)
    let y = line_y(0, i)
    place(
      top + left,
      dx: x_start(0) + 0.05cm,
      dy: y - 1em,
      text[
        #box(width: 0.55em)[#align(right)[#text(size: 0.75em)[#seed]]].#h(0.5em)#if bye [#h(0.3em)#text(fill: luma(160))[---]] else [#name]
      ],
    )
  }

  // Auto-advance fencers with a bye into round 1 (semifinals column).
  for match_i in range(0, 4) {
    let seed_a = seed_order.at(match_i * 2)
    let seed_b = seed_order.at(match_i * 2 + 1)
    let bye_a = is_bye.at(seed_a - 1)
    let bye_b = is_bye.at(seed_b - 1)
    let winner = if bye_a { fencers.at(seed_b - 1) } else if bye_b { fencers.at(seed_a - 1) } else { none }
    if winner != none {
      let y = line_y(1, match_i)
      place(
        top + left,
        dx: x_start(1) + 0.05cm,
        dy: y - 1em,
        text[#winner],
      )
    }
  }
})