#set page(paper: "a4", margin: 0.75cm)
#set text(font: "GFS Neohellenic", size: 11pt)


// ----- Fencers (seed order: index 0 = seed 1) ----------------
// Generated by render_elim.py: #let fencers and #let is_bye arrays.
// Slots beyond the actual entry count are filled with [ #h(1em) ---] (bye).
{{fencers}}

// Standard 64-bracket seeding (1v64, 32v33, 16v49, 17v48, ...)
// Top half of the bracket (32 entries) — page 1
#let seed_order_top = (
   1, 64, 32, 33, 16, 49, 17, 48,
   8, 57, 25, 40,  9, 56, 24, 41,
   4, 61, 29, 36, 13, 52, 20, 45,
   5, 60, 28, 37, 12, 53, 21, 44,
)
// Bottom half (32 entries) — page 2
#let seed_order_bot = (
   2, 63, 31, 34, 15, 50, 18, 47,
   7, 58, 26, 39, 10, 55, 23, 42,
   3, 62, 30, 35, 14, 51, 19, 46,
   6, 59, 27, 38, 11, 54, 22, 43,
)

// ----- Drawing parameters (shared by both pages) -------------
#let draw_w = 27.7cm
#let draw_h = 25.5cm
#let n = 32
#let col_count = 7
#let col_w = draw_w / col_count
#let row_h = draw_h / n
#let stroke_style = 0.5pt + black

#let line_y(r, i) = {
  let step = calc.pow(2, r)
  (i * step + (step - 1) / 2 + 0.5) * row_h
}
#let entries(r) = calc.div-euclid(n, calc.pow(2, r))
#let x_start(r) = r * col_w + 0.15cm
#let x_end(r) = (r + 1) * col_w - 0.15cm

#let render_half(half_label, seeds, tail_label, show_final_line) = {

  place(
  top + center,
  scope: "parent",
  float: true,
  text(1.4em, weight: "bold")[
    {{tournament}} #h(1fr) {{discipline}} -- elimination (#half_label)
  ],
  )

  grid(
    columns: (1fr,) * 5,
    align: center,
    text(weight: "bold")[Round of 64],
    text(weight: "bold")[Round of 32],
    text(weight: "bold")[Round of 16],
    text(weight: "bold")[Quarterfinals],
    text(weight: "bold")[Semifinals],
  )
  v(0.1cm)

  block(width: draw_w, height: draw_h, {
    // Match lines, vertical connectors, feed stubs (rounds 0..4)
    for r in range(0, 5) {
      let count = entries(r)
      let i = 0
      while i < count {
        let y = line_y(r, i)
        let xs = x_start(r)
        let xe = x_end(r)

        place(
          top + left,
          dx: xs,
          dy: y,
          line(length: xe - xs, stroke: stroke_style),
        )

        if calc.rem(i, 2) == 0 {
          let y2 = line_y(r, i + 1)
          let mid = (y + y2) / 2

          place(
            top + left,
            dx: xe,
            dy: y,
            line(angle: 90deg, length: y2 - y, stroke: stroke_style),
          )
          if r < 4 {
          place(
            top + left,
            dx: xe,
            dy: mid,
            line(length: x_start(r + 1) - xe, stroke: stroke_style),
          ) } else {
           place(
            top + left,
            dx: xe,
            dy: mid,
            line(length: x_start(r) - xe, stroke: stroke_style),
          )
          }
        }
        i = i + 1
      }
    }

    // Column 6: semifinalist line (always present)
    let sf_y = (line_y(4, 0) + line_y(4, 1)) / 2



    // Fencer names above their round-of-64 lines.
    // Byes are shown in grey without a seed number.
    for i in range(0, 32) {
      let seed = seeds.at(i)
      let name = fencers.at(seed - 1)
      let bye = is_bye.at(seed - 1)
      let y = line_y(0, i)
      place(
        top + left,
        dx: x_start(0) + 2pt,
        dy: y - 0.85em,
        text[
          #box(width: 0.55em)[#align(right)[#text(size: 8pt)[#seed]]].#h(0.1em)#if bye [#h(0.3em)#text(fill: luma(160))[---]] else [#name]
        ],
      )
    }

    // Auto-advance fencers with a bye into round 1 (round-of-32 column).
    for match_i in range(0, 16) {
      let seed_a = seeds.at(match_i * 2)
      let seed_b = seeds.at(match_i * 2 + 1)
      let bye_a = is_bye.at(seed_a - 1)
      let bye_b = is_bye.at(seed_b - 1)
      let winner = if bye_a { fencers.at(seed_b - 1) } else if bye_b { fencers.at(seed_a - 1) } else { none }
      if winner != none {
        let y = line_y(1, match_i)
        place(
          top + left,
          dx: x_start(1) + 2pt,
          dy: y - 0.85em,
          text[#winner],
        )
      }
    }
  })
}

// ----- Page 1: top half -------------------------------------
#render_half("1/2", seed_order_top, "", false)

#pagebreak()

// ----- Page 2: bottom half ----------------------------------
#render_half("2/2", seed_order_bot, "", true)