#set page(paper: "a4", margin: 1cm)
#set text(font: "GFS Neohellenic", size: 12pt)

#place(
  top + center,
  scope: "parent",
  float: true,
  text(1.4em, weight: "bold")[
    {{tournament}} #h(1fr) {{discipline}} -- elimination
  ],
)

// ----- Fencers (seed order: index 0 = seed 1) ----------------
// Generated by render_elim.py: #let fencers and #let is_bye arrays.
// Slots beyond the actual entry count are filled with [ #h(1em) ---] (bye).
{{fencers}}

// Standard 32-bracket seeding (1v32, 16v17, 8v25, 9v24, ...)
#let seed_order = (
   1, 32, 16, 17,  8, 25,  9, 24,
   4, 29, 13, 20,  5, 28, 12, 21,
   2, 31, 15, 18,  7, 26, 10, 23,
   3, 30, 14, 19,  6, 27, 11, 22,
)

// ----- Title + column headers -------------------------------

#grid(
  columns: (1fr,) * 4,
  align: center,
  text(weight: "bold")[Round of 32],
  text(weight: "bold")[Round of 16],
  text(weight: "bold")[Quarterfinals],
  text(weight: "bold")[Semifinals],
)

#v(0.1cm)

// ----- The bracket ------------------------------------------
#let draw_h = 25.5cm
#let draw_w = 28cm

#let n = 32
#let col_count = 6
#let col_w = draw_w / col_count
#let row_h = draw_h / n

#let line_y(r, i) = {
  let step = calc.pow(2, r)
  (i * step + (step - 1) / 2 + 0.5) * row_h
}
#let entries(r) = calc.div-euclid(n, calc.pow(2, r))
#let x_start(r) = r * col_w + 0.15cm
#let x_end(r) = (r + 1) * col_w - 0.15cm

#let stroke_style = 0.5pt + black

// Render the bracket as nested place() inside a sized box.
// Using block() with explicit width/height as the positioning anchor.
#block(width: draw_w, height: draw_h, {
  // Match lines, connectors, and feed stubs for rounds 0..4
  for r in range(0, 5) {
    let count = entries(r)
    let i = 0
    while i < count {
      let y = line_y(r, i)
      let xs = x_start(r)
      let xe = x_end(r)
      let width = xe - xs

      // Horizontal match line
      place(
        top + left,
        dx: xs,
        dy: y,
        line(length: width, stroke: stroke_style),
      )

      if calc.rem(i, 2) == 0 {
        let y2 = line_y(r, i + 1)
        let mid = (y + y2) / 2

        // Vertical connector
        place(
          top + left,
          dx: xe,
          dy: y,
          line(angle: 90deg, length: y2 - y, stroke: stroke_style),
        )

        // Stub feeding into next round
        place(
          top + left,
          dx: xe,
          dy: mid,
          line(length: x_start(r + 1) - xe, stroke: stroke_style),
        )
      }

      i = i + 1
    }
  }

  // Winner line (col 6)
  let winner_y = (line_y(4, 0) + line_y(4, 1)) / 2
  place(
    top + left,
    dx: x_end(4),
    dy: winner_y,
    line(length: x_end(5) - x_end(4), stroke: stroke_style),
  )

  // Fencer names above their round-of-32 lines.
  // Byes are shown in grey without a seed number.
  for i in range(0, 32) {
    let seed = seed_order.at(i)
    let name = fencers.at(seed - 1)
    let bye = is_bye.at(seed - 1)
    let y = line_y(0, i)
    place(
      top + left,
      dx: x_start(0) + 0.05cm,
      dy: y - 0.32cm,
      text[
        #box(width: 0.55em)[#align(right)[#text(size: 8pt)[#seed]]].#h(0.1em)#if bye [#h(0.3em)#text(fill: luma(160))[---]] else [#name]
      ],
    )
  }

  // Auto-advance fencers with a bye into round 1 (round-of-16 column).
  for match_i in range(0, 16) {
    let seed_a = seed_order.at(match_i * 2)
    let seed_b = seed_order.at(match_i * 2 + 1)
    let bye_a = is_bye.at(seed_a - 1)
    let bye_b = is_bye.at(seed_b - 1)
    let winner = if bye_a { fencers.at(seed_b - 1) } else if bye_b { fencers.at(seed_a - 1) } else { none }
    if winner != none {
      let y = line_y(1, match_i)
      place(
        top + left,
        dx: x_start(1) + 0.05cm,
        dy: y - 0.32cm,
        text[#winner],
      )
    }
  }
})